### ISSUE TITLE
Failed to `Setup LikeCoin chain mainnet node`

### ISSUE THREAD

**Issue by askender** [likecoin/likecoin-chain#32]
I follow the steps as <https://github.com/likecoin/likecoin-chain/wiki/Setup-LikeCoin-chain-mainnet-node>
And I found that, the output of `docker-compose logs` is:
```
Attaching to likechain_liked
likechain_liked | getting external IP address
likechain_liked | Got external IP: 167.172.206.151
likechain_liked | p2p.external_address = tcp://167.172.206.151:26656
likechain_liked | I[2020-03-16|04:59:18.719] starting ABCI with Tendermint                module=main
likechain_liked | ERROR: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain
```

I guess that:
We should add a step before `docker-compose up -d`,  similar to 
```
After step 1, a Cosmos address for the validator will be initialized. Send the address to us and we will send some token into the account for staking.
```
which is described in <https://github.com/likecoin/likecoin-chain/blob/master/README.md>

My address is cosmos1fczdv93strevfmvc3fyv3zyrmckcnn2pvuvqul

Best wishes!

**Comment by nnkken** [comment]
The README was for the old testnet and is not updated.

Please refer to https://docs.like.co/developer/likecoin-chain-node/setup-mainnet-node for the newest documents. The new document also includes some concept introductions, which you may want to refer to for a validator node.

You will need to remove `.liked`, `.likecli` and `docker-compose.yml` before following the new setup, to prevent files generated from the old setup blocking the new setup. This will also reset the Cosmos address generated.

**Comment by nnkken** [comment]
I think you haven't download the correct `genesis.json`? What is the content of `.liked/config/genesis.json`?

**Comment by askender** [comment]
@nnkken   Thanks.  It is because I didn't remove `.liked`, `.likecli` and `docker-compose.yml`.
This problem has been solved now.
