### ISSUE TITLE
scripts/build.sh Error

### ISSUE THREAD

**Issue by sunnydreamfly** [likecoin/likecoin-chain#33]
developer@wzserver:~/LikeCoin/likecoin-chain$ sudo ./scripts/build.sh 
Sending build context to Docker daemon  224.8kB
Step 1/8 : FROM golang:1.13-alpine
 ---> 3369136a43d1
Step 2/8 : RUN apk update && apk add --no-cache build-base git bash curl linux-headers ca-certificates
 ---> Using cache
 ---> c06bfc214182
Step 3/8 : WORKDIR /
 ---> Using cache
 ---> 9b5e55540b7b
Step 4/8 : RUN mkdir -p ./likechain
 ---> Using cache
 ---> ca6039eef936
Step 5/8 : COPY ./go.mod ./likechain/go.mod
 ---> Using cache
 ---> 4c5559cb9339
Step 6/8 : COPY ./go.sum ./likechain/go.sum
 ---> Using cache
 ---> a26a742ed7f0
Step 7/8 : WORKDIR /likechain
 ---> Using cache
 ---> 741f4697159e
Step 8/8 : RUN go mod download
 ---> Running in 72b45328e8d4
go: github.com/btcsuite/btcd@v0.0.0-20191010011042-988181ef23fa: Get https://proxy.golang.org/github.com/btcsuite/btcd/@v/v0.0.0-20191010011042-988181ef23fa.mod: dial tcp 216.58.200.241:443: i/o timeout
The command '/bin/sh -c go mod download' returned a non-zero code: 1

Set Docker Proxy  HTTP& HTTPS  failed

**Comment by rickmak** [comment]
No longer valid.
