### ISSUE TITLE
Initialization failed

### ISSUE THREAD

**Issue by airled** [likecoin/likecoin-chain#36]
HI. I use [this manual](https://docs.like.co/developer/likecoin-chain-node/setup-mainnet-node) to run a node. I built image and downloaded `genesis.json`. But when I run init script:
```
[~/likecoin-chain] > sudo ./scripts/init.sh airled genesis.json 913bd0f4bea4ef512ffba39ab90eae84c1420862@34.82.131.35:26656
Unable to find image 'likechain/likechain:sheungwan' locally
docker: Error response from daemon: pull access denied for likechain/likechain, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```
Seems like script tries to run incorrect image.

**Comment by rickmak** [comment]
Yes, the image tag in build.sh and /script/init.sh is not matching. Let me send a quick fix.
