### ISSUE TITLE
Enable state sync snapshot in default app.toml

### ISSUE THREAD

**Issue by williamchong** [likecoin/likecoin-chain#58]
Should we set statesync snapshot on in our default app.toml?
This would allow easier statesync in the future, e.g. osmosis default is 1500 x 2

**Comment by rickmak** [comment]
Yes, agree.

**Comment by rickmak** [comment]
The default tutorial already ask validator enable state sync, refs: https://github.com/likecoin/dao/commit/67598675629176f510436ebc9fc7edd35a99b47a

It working well in likecoin-public-testnet-4 so far.
